# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$os$directory$git_branch$lua$rust$python$terraform$kubernetes$fill$azure$aws
$status$character """

palette = "catppuccin_macchiato"

[fill]
symbol = ' '

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[directory]
truncation_length = 6 
truncation_symbol = '…/'
style = 'bold mauve'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
[status]
symbol = '[ ](bold red)'
success_symbol = '[ ](bold green)'
format = '[$symbol$signal_name$maybe_int]($style) '
map_symbol = true
disabled = false

# LANGUAGES
[lua]
format = 'using [ $version](bold blue) '
[rust]
format = 'using [ $version](red bold) '
[python]
symbol = 'using [ $version](bold green)'
pyenv_version_name = true
[terraform]
format = 'using [󱁢 $version]($style) '
[git_branch]
symbol = ' '
truncation_length = 20 
truncation_symbol = ''
ignore_branches = ['master', 'main']

# CLOUD PLATFORMS
[azure]
disabled = false
format = '[$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'
[aws]
format = '[$symbol($profile )($region)]($style)'
symbol = '  '
style = 'bold peach'


# CONTAINERS AND ORCHESTRATION
[kubernetes]
format = 'connected to [󱃾 ($cluster)](bold yellow) '
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
]

# OS RELATED
[os]
format = "[$symbol]($style) [($name) ]($style)"
style = "bold blue"
disabled = false
[os.symbols]
Windows = ""
Arch = "󰣇"
